modLoader = "javafml" #mandatory
loaderVersion = "[4,)" #mandatory
license = "MIT" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId = "flipside" #mandatory
version = "${mod_version}" #mandatory
displayName = "Flipside" #mandatory

#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)

logoFile="logo.png" #optional
credits="" #optional
authors = "Siuolplex" #optional
description = '''Another world, flipped upside down''' #mandatory (Supports multiline text)

[[mixins]]
config = "flipside.mixins.json"

[[mixins]]
config = "flipside.neoforge.mixins.json"

[[dependencies.flipside]]
modId = "neoforge"
type="required" #(Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[21.10.47-beta,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.flipside]]
modId = "minecraft"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"
